xApplication: xApplication

server:
  port: 8080

graphql:
  servlet:
    # Sets if GraphQL servlet should be created and exposed. If not specified defaults to "true".
    enabled: false
    # Sets the path where GraphQL servlet will be exposed. If not specified defaults to "/graphql"
    mapping: /xxxgraphql
    cors-enabled: true
    cors:
      allowed-origins: http://some.domain.com
      allowed-methods: GET, HEAD, POST
    # if you want to @ExceptionHandler annotation for custom GraphQLErrors
    exception-handlers-enabled: true
    graphiql:
      mapping: /zzzzzgraphiql
      basePath: /xx
      enabled: true
      pageTitle: GraphiQL
      cdn:
        enabled: true
        version: latest
      props:
        resources:
          query: query.graphql
          defaultQuery: defaultQuery.graphql
          variables: variables.json
        variables:
          editorTheme: "solarized light"


management:
  health:
    livensstate:
      enabled: true
    rediinessstate:
      enabled: true
    endpoints:
      enabled-by-default: true
      web:
        exposure:
          include: "health,info,metrics,prometheus,startup"
    endpoint:
      health:
        show-details: always
        show-components: always
        enabled: true
      info:
        enabled: true
      metrics:
        enabled: true
      startup:
        enabled: true
    info:
      git:
        mode: full
        env:
          enabled: true
        defaults:
          enabled: true

